v5.0/operation-manual/cluster-management/node-health.md
v5.0/user-manual/app-creation/creation-process.md
v5.0/user-manual/app-creation/way-of-creation.md

1. enrich the content of creating apps with images
2. adjust the language of the source code creation support

[ADD] enrich the content of creating apps with images

---

v5.0/user-manual/app-creation/language-support/golang.md
v5.0/user-manual/app-creation/language-support/php.md
v5.0/user-manual/app-creation/language-support/python.md

[REV] update lang docs

---

_includes/5.0/best-practice.json
css/theme-blue.css
recruitment/join.md

1. modify wrong character and click navigation bar refresh error
2. modify table css

[REV] modify wrong character and click navigation bar refresh error

---

v5.0/user-manual/app-manage/app/app-topology.md
v5.0/user-manual/app-store/app-market.md

[FIX] fix edit the topology diagram document

 [FIX] fix edit the topology diagram document

---

v5.0/advanced-scenarios/rainbond-devops.md

- 更新自动部署的文档：
- 明确回调信息使用的数据格式为json

[UPDATE] Perfect auto CD @deploy

---

v5.0/user-manual/app-manage/app/app-topology.md

[REV] Modify and edit the topology document

---

v5.0/operation-manual/install/HA/install-base-ha.md

[update] update install-base-ha.md for details @deploy

[update] update install-base-ha.md for details @deploy

---

_includes/5.0/advanced-scenarios.json
v5.0/advanced-scenarios/application-delivery.md

[ADD] add application-delivery.md @deploy
添加文档 通过应用市场做应用交付与升级

[ADD] add application-delivery.md @deploy

---

css/customstyles.css
css/openSourcePage.css

[REV] Modify the file style

---

_includes/topnav.html
_www/index.html
_www/indextwo.html
css/customstyles.css
v5.0/advanced-scenarios/overview.md

[ADD] Modify the Style antd Height

---

content/user-manual/app-service-manage/thirdparty-manage.md

[FIX] wrong link

---

content/user-operations/monitor/monitor-alter-items.md

description of gateway related metrics

description of gateway related metrics

---

content/user-manual/app-service-manage/service-env.md

[ADD] convert domains to envs

---

content/enterprise_service.md

update  @deploy

---

content/user-operations/management/data migration.md

ADD  data migration@deploy

---

content/user-operations/management/data migration.md

update data migration

---

content/user-manual/app-creation/creation-process.md
content/user-manual/app-creation/service_create.md
content/user-operations/install/install-base-ha.md
content/user-operations/trouble-shooting/pt-faq.md

更新git构建应用时子目录添加方式

---

content/user-operations/component/rbd-gateway.md
content/user-operations/tools/grctl.md

fix: update  rbd-gateway config name

:bug: currenct gateway config is gateway.yaml, not lb.yaml

---

content/upgrade/5.1.7-5.1.8.md
content/user-operations/install/online_install.md

[ADD] 5.1.8 release docs

---

content/user-operations/storage/centosgfs.md
content/user-operations/storage/ubuntugfs.md

update gfs storage

---

content/user-operations/gha/centos_keepalived.md
content/user-operations/gha/ubuntu_keepalived.md
content/user-operations/install/offline_install.md
content/user-operations/management/node.md

1.Update offline installation package to 5.1.9
2.Keepalived is set to no preemption mode
3.Correct node expansion attribute identification error

Update offline installation package to 5.1.9

---

content/Troubleshoot/concrete-operations/Issue k8s certificate.md

Update Issue k8s certificate.md

---

content/docs/user-manual/app-service-manage/custom-volume/ali-disk.md
content/docs/user-manual/app-service-manage/custom-volume/ceph-rbd.md
content/docs/user-manual/app-service-manage/service-volume-custom.md

新增存储的描述以及阿里云盘和ceph-rbd存储的安装使用文档

update install progress

---

themes/rainbond/static/css/easydropdown.css

[add]  Switch version Select

---

content/docs/user-operations/install/install-from-rancher.md

install rainbond

---

content/docs/user-manual/plugin-manage/mesh-plugin.md

mesh plugin desc

---

content/docs/user-manual/plugin-manage/new-plugin.md

修改数据库备份和恢复文档，作为插件制作文档示例
1、添加插件设计
2、调整原有文档格式
3、去除无用图片展示

new plugin

---

content/docs/get-start/best-practices/work_with_elk.md

1、修改 日志对接 ELK 体系 文档，使用默认插件 fileBeat日志收集插件 进行实践，
2、去除无用图片
3、添加常见问题

update elk log docs

---

content/docs/install/install-from-k8s/high-availability.md
content/docs/install/install-from-k8s/minimal-install.md
content/docs/install/install-from-linux/high-availability.md
content/docs/install/install-from-linux/minimal-install.md
content/docs/quick-start/quick-install.md
content/docs/user-operations/install/kubernetes-install.md
content/docs/user-operations/install/troubleshooting.md

在安装文档中引入无法选择网关节点的链接

---

themes/rainbond/layouts/partials/medium.html

Modify the images

---

themes/rainbond/layouts/index.html
themes/rainbond/layouts/partials/footer.html
themes/rainbond/layouts/partials/header.html
themes/rainbond/static/css/style.css
themes/rainbond/static/js/visitor.js

Modify the text @deploy

---

themes/rainbond/layouts/index.html
themes/rainbond/static/css/style.css

Modify the text color @deploy

---

content/docs/quick-start/quick-install.md

install nfs client

---

themes/rainbond/layouts/partials/header.html

Modify the  document address

---

themes/rainbond/layouts/_default/single.html
themes/rainbond/static/css/documentation.css

Modify the  document bottom

---

content/docs/install/install-from-hosted-provider/install-on-cce.md
content/docs/install/install-from-hosted-provider/install-on-tke.md

1. 在华为云的 CCE 上安装 Rainbond，并对接到 Rainbond Cloud.
2. 在华为云的 TKE 上安装 Rainbond，并对接到 Rainbond Cloud.

Install on cce

---

content/docs/install/install-from-hosted-provider/install-on-eks.md

在 Amazon EKS 上安装 Rainbond Cloud

install on eks

---

themes/rainbond/layouts/_default/dashboard.html
themes/rainbond/layouts/partials/footer.html
themes/rainbond/layouts/partials/header.html
themes/rainbond/static/css/doc-dashboard.css

Modify the text and Jump address

---

content/docs/upgrade/5.2.2-5.3.1.md
content/docs/upgrade/5.3.0-upgrade.md

5.2.2 升级到 5.3.0 的文档改为 5.2.2 升级到 5.3.1

5.2.2 upgrade to 5.3.1

---

content/docs/upgrade/5.2.2-5.3.1.md

incompatible  table format

---

content/docs/user-manual/component-op/service-log.md

add component log docs

---

content/docs/opensource-app/tdengine.md

[TDengine.md](https://github.com/goodrain/rainbond-docs/files/7473002/TDengine.md)

Update tdengine.md  集群版TDengine编辑更新

---

content/docs/upgrade/5.5.0-upgrade.md

Create 5.5.0-upgrade.md   5.4.0升级5.5.0文档

---

config.yaml
content/docs/quick-start/quick-install.md

V5.5更新快速安装

---

docs/installation/install-with-helm/ack-install-with-helm.md
docs/installation/install-with-helm/cce-install-with-helm.md
docs/installation/install-with-helm/install-from-rancher.md
docs/installation/install-with-helm/k8s-install-with-helm.md
src/components/Swiper/index.js
versioned_docs/version-v5.5/user-operations/deploy/install-with-helm/k8s-install-with-helm.md

Signed-off-by: zhangqi <13651281168@163.com>

fix: link err and video link err

---

docs/installation/install-with-ui/ha-installation.md

Signed-off-by: zhangqi <13651281168@163.com>

fix: err link

---

docs/api/Intro.md
docusaurus.config.js
sidebars.js

docs: add instructions for using openapi

---

src/pages/index.js

remove the logo

---

community/contribution/index.md

docs: add submit message specification

---

src/pages/index.js

feat: add application demo entry

---

package.json
src/components/DiaLog/index.tsx
src/components/NavBar/index.js
src/components/Swiper/index.js
src/pages/index.js
src/theme/Navbar/Layout/index.tsx
yarn.lock

docs: add github star diglog

---

src/components/NavBar/index.js
src/pages/enterprise_server/index.js
src/pages/enterprise_server/index.module.scss
src/pages/index.js
src/pages/index.module.scss

fix: home page add follow rainbond

---

src/pages/enterprise_server/index.js

fix: change text

---

src/pages/enterprise_server/index.js
src/pages/index.js
src/pages/index.module.scss

fix: change the button

---

src/components/DAinput/BuildInput.js
src/components/DAinput/DAinput.js
src/components/DAinput/Etcd.js
src/components/Helm/Helm.js
src/components/Helm/index.scss

fix: helm command generation tool

---

docusaurus.config.js
src/components/NavBar/index.js

chore: adjust document jump links

---

Dockerfile

feature: modify dockerfile

---

src/theme/BlogLayout/index.tsx
src/theme/BlogPostItem/index.tsx

fix: case and usescene page style err

---

Dockerfile

fix: build err

---

docusaurus.config.js

docs: v5.7 archive

---

versionsArchived.json

docs: add v5.7 docs

---

docs/use-manual/app-manage/k8s-resource/k8s-resource.md
docs/use-manual/team-manage/ns-to-team/ns-to-team.md
sidebars.js

Signed-off-by: zhangsetsail <zqh15131121078@126.com>

feat: k8s resource creation and cluster application import document

---

docs/use-manual/component-create/package-support/yaml.md

Signed-off-by: zhangsetsail <zqh15131121078@126.com>

feat: push yaml docs

---

community/change/5.8.0.md
docs/upgrade/5.8.0-upgrade.mdx
sidebars.js

docs: add version change and upgrade documents

---

src/theme/BlogLayout/index.tsx

fix: style err

---

src/pages/enterprise_server/index.js

fix: Enterprise Edition view adds ARM support

---

src/pages/enterprise_server/index.js

fix: Arm Change to offline environment

---

sidebars.js

docs: del offline

---

docusaurus.config.js
src/components/NavBar/index.js
src/pages/index.tsx
src/theme/Navbar/Content/index.tsx

perf: adjust the quick start jump link

---

docs/installation/install-troubleshoot/dind-install-troubleshoot.md
docs/installation/install-troubleshoot/helm-install-troubleshoot.md
docs/installation/install-troubleshoot/index.md
docs/installation/install-troubleshoot/ui-install-troubleshoot.md
docs/installation/install-with-dind.mdx
docs/installation/install-with-helm/ack-install-with-helm.md
docs/installation/install-with-helm/cce-install-with-helm.md
docs/installation/install-with-helm/install-from-rancher.md
docs/installation/install-with-helm/k3s-install-with-helm.md
docs/installation/install-with-helm/k8s-install-with-helm.mdx
docs/installation/install-with-ui/host-install-with-ui.md
docs/installation/install-with-ui/offline-install.md
docs/ops-guide/troubleshoot/cluster_troubleshooting.md
docs/quick-start/getting-started.mdx
docs/use-manual/usage_troubleshooting.md

perf: add troubleshooting methods for installation problems

---

i18n/en/docusaurus-plugin-content-docs/current.json
i18n/en/docusaurus-plugin-content-docs/current/installation/install-with-dind.mdx
i18n/en/docusaurus-plugin-content-docs/current/quick-start/introduction.md
i18n/en/docusaurus-plugin-content-docs/current/quick-start/quick-install.mdx

fix: translation en

---

docs/installation/install-with-dind.mdx
docs/installation/offline/index.mdx
i18n/en/docusaurus-plugin-content-docs/current/installation/install-with-dind.mdx
i18n/en/docusaurus-plugin-content-docs/current/installation/install-with-ui/ha-installation.md
i18n/en/docusaurus-plugin-content-docs/current/installation/install-with-ui/host-install-with-ui.md

fix: incorrect installation commands and instructions

---

i18n/en/code.json
i18n/en/docusaurus-theme-classic/footer.json
i18n/en/docusaurus-theme-classic/navbar.json
src/css/custom.css
src/pages/index.tsx
src/pages/opensourceApps/index.tsx

fix: sytle err and add link

---

blog/2022-02-15-knowstreaming.md
i18n/en/code.json
src/pages/opensourceApps/_components/Users/index.tsx

feature: add translate and modify blog

---

src/pages/enterprise_server/index.js
src/pages/index.module.scss

fix: Add an appointment demo link

---

i18n/en/code.json
src/components/NavBar/index.js
src/components/NavBar/index.module.scss

feature: add navbar dropdown

---

i18n/en/code.json
src/pages/opensourceApps/_components/Users/index.tsx

fix: modify ks desc

---

src/pages/index.tsx

page: del command

---

src/components/Swiper/caluso.css

fix: img link err

---

community/change/5.9.0.md
docs/upgrade/5.9.0-upgrade.mdx
sidebars.js
src/components/HomePage/Command/index.tsx

docs: add version changes and release documents

---

src/components/HomePage/Command/index.tsx

feature: modify quick start command

---

i18n/en/code.json
src/components/HomePage/Command/index.tsx
src/components/HomePage/Command/styles.module.css
src/components/HomePage/Feature/styles.module.css
src/components/HomePage/JoinCommunity/index.tsx

fix: change command and some problem

---

nginx.conf

feature: switch url to browser language

---

docs/installation/install-with-helm/vaules-config.md

fix: helm chart parameters err

---

community/change/5.10.0.md
docs/installation/ha-deployment/deploy-k8s/index.md
docs/installation/install-with-dind.mdx
docs/installation/install-with-ui/index.md
docs/installation/install-with-ui/migrate-app.md
docs/installation/offline/index.mdx
docs/ops-guide/tools/grctl.md
docs/quick-start/quick-install.mdx
docs/upgrade/5.10.0-upgrade.mdx
docs/use-manual/component-create/helm-support/creation-process.md
docs/use-manual/component-create/helm-support/helm-cmd-install.md
docs/use-manual/component-create/helm-support/index.md
docs/use-manual/component-create/helm-support/manage-helm-app.md
i18n/en/docusaurus-plugin-content-docs/current.json
i18n/en/docusaurus-plugin-content-docs/current/use-manual/app-store-manage/export-non-container-package.md
i18n/en/docusaurus-plugin-content-docs/current/use-manual/component-create/helm-support/creation-process.md
i18n/en/docusaurus-plugin-content-docs/current/use-manual/component-create/helm-support/helm-cmd-install.md
i18n/en/docusaurus-plugin-content-docs/current/use-manual/component-create/helm-support/manage-helm-app.md
sidebars.js

Signed-off-by: zhangsetsail <zqh15131121078@126.com>

 feat: v5.10.0 version docs 

---

versionsArchived.json

docs: add v5.9 docs

---

.github/workflows/main-actions.yml

docs: modify action env

---

docs/installation/ha-deployment/console-recover.md

Signed-off-by: zhangsetsail <zqh15131121078@126.com>

perf: optimize console high availability deployment migration doc

---

docs/installation/install-with-helm/other/k3s-install-with-helm.md
docs/installation/install-with-helm/vaules-config.md

fix: install on k3s containerd

---

docs/installation/install-troubleshoot/dind-install-troubleshoot.md
docs/installation/install-troubleshoot/helm-install-troubleshoot.md
docs/installation/install-troubleshoot/ui-install-troubleshoot.md
docs/installation/install-with-helm/install-from-kubernetes.md
docs/use-manual/usage_troubleshooting.md

perf: self-built k8s cluster installation document

---

docs/installation/install-with-helm/cloud/ack-install-with-helm.md

fix: install to ack

---

docs/installation/ha-deployment/overview/index.md
docs/installation/install-with-ui/index.md

feat: support anolis

---

versionsArchived.json

docs: add v5.10

---

sidebars.js

docs: temporary removal of cluster nodes management guide

---

docs/troubleshooting/use/cluster-connect.md

修正证书对应关系描述信息

---

docs/use-manual/component-manage/env/advanced-env.md

Add the example for ES_HOST_DOMAINNAME.

feat: add the example for ES_HOST_DOMAINNAME

---

community/change/5.15.1.md
docs/installation/ha-deployment/console-recover.md
docs/installation/ha-deployment/deploy-k8s/index.md
docs/installation/install-with-helm/vaules-config.md
docs/installation/install-with-ui/index.md
docs/installation/offline/index.md
docs/ops-guide/tools/grctl.md
docs/troubleshooting/installation/ui.md
docs/troubleshooting/use/run.md
docs/upgrade/latest-version.md
docs/versions.md

docs: v5.15.1-release

---

docs/installation/install-with-helm/install-from-kubernetes.md
docs/installation/install-with-helm/vaules-config.md

docs: helm chart optimize

---

docs/kubernetes-native-guide/import-manage/special-attribute.md

Amend the misspelling, it should be 'postStart', not 'ostStart'.

fix: amend the misspelling, it should be 'postStart', not 'ostStart'
